<?php

namespace AppBundle\Repository;

/**
 * CooperativaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CooperativaRepository extends \Doctrine\ORM\EntityRepository
{
}
