<?php

namespace AppBundle\Repository;

/**
 * ReservasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservasRepository extends \Doctrine\ORM\EntityRepository
{
}
